/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Notatnik;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author student
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoOProgramie = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        onkoOtworz = new javax.swing.JFileChooser();
        oknoZapisz = new javax.swing.JFileChooser();
        opcjaZapisu = new javax.swing.JOptionPane();
        tab1 = new javax.swing.JTabbedPane();
        tab3 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        PanelTextowy = new javax.swing.JScrollPane();
        poleTextowe = new javax.swing.JTextPane();
        tab2 = new javax.swing.JTabbedPane();
        panel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPlik = new javax.swing.JMenu();
        menuZapisz = new javax.swing.JMenuItem();
        menuWczytaj = new javax.swing.JMenuItem();
        menuZamknij = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuZakoncz = new javax.swing.JMenuItem();
        menuPomoc = new javax.swing.JMenu();
        menuOProdramie = new javax.swing.JMenuItem();

        oknoOProgramie.setTitle("O Programie");
        oknoOProgramie.setLocation(new java.awt.Point(750, 400));
        oknoOProgramie.setMinimumSize(new java.awt.Dimension(250, 100));

        jLabel1.setText("Autor: Szymon Kowalski");

        jLabel2.setText("Program Notatnik v 0.0.2.6.7.0,1 G ");

        javax.swing.GroupLayout oknoOProgramieLayout = new javax.swing.GroupLayout(oknoOProgramie.getContentPane());
        oknoOProgramie.getContentPane().setLayout(oknoOProgramieLayout);
        oknoOProgramieLayout.setHorizontalGroup(
            oknoOProgramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoOProgramieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oknoOProgramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(oknoOProgramieLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        oknoOProgramieLayout.setVerticalGroup(
            oknoOProgramieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoOProgramieLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 250, Short.MAX_VALUE))
        );

        jMenuItem1.setText("jMenuItem1");

        oknoZapisz.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        oknoZapisz.setDialogTitle("Zapisz");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 400));

        PanelTextowy.setViewportView(poleTextowe);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTextowy, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTextowy, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab3.addTab("Panel 1", panel1);

        tab1.addTab("Zakladka 1", tab3);

        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab2.addTab("Panel2", panel2);

        tab1.addTab("Zakladka2", tab2);

        menuPlik.setText("Plik");
        menuPlik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPlikActionPerformed(evt);
            }
        });

        menuZapisz.setText("Zapisz");
        menuZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuZapiszActionPerformed(evt);
            }
        });
        menuPlik.add(menuZapisz);

        menuWczytaj.setText("Wczytaj");
        menuWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWczytajActionPerformed(evt);
            }
        });
        menuPlik.add(menuWczytaj);

        menuZamknij.setText("Zamknij");
        menuZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuZamknijActionPerformed(evt);
            }
        });
        menuPlik.add(menuZamknij);
        menuPlik.add(jSeparator1);

        menuZakoncz.setText("Zakoncz");
        menuZakoncz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuZakonczActionPerformed(evt);
            }
        });
        menuPlik.add(menuZakoncz);

        jMenuBar1.add(menuPlik);

        menuPomoc.setText("Pomoc");

        menuOProdramie.setText("O programie");
        menuOProdramie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOProdramieActionPerformed(evt);
            }
        });
        menuPomoc.add(menuOProdramie);

        jMenuBar1.add(menuPomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tab1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOProdramieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOProdramieActionPerformed
        oknoOProgramie.setVisible(true);
    }//GEN-LAST:event_menuOProdramieActionPerformed

    private void menuWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWczytajActionPerformed
        onkoOtworz.showOpenDialog(this);
        File plik = onkoOtworz.getSelectedFile();
        try {
            poleTextowe.read(new FileReader(plik.getAbsolutePath()), null);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuWczytajActionPerformed

    private void menuZakonczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuZakonczActionPerformed

    }//GEN-LAST:event_menuZakonczActionPerformed

    private void menuZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuZapiszActionPerformed
        oknoZapisz.showOpenDialog(this);
        File plik = oknoZapisz.getSelectedFile();
        try {
            FileWriter wynik = new FileWriter(plik);
            wynik.write(poleTextowe.getText());
            wynik.close();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_menuZapiszActionPerformed

    private void menuZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuZamknijActionPerformed
        opcjaZapisu.setVisible(true);
        Object opcje ={"Tak","Nie","Anuluj"};
        
    }//GEN-LAST:event_menuZamknijActionPerformed

    private void menuPlikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPlikActionPerformed
       
    }//GEN-LAST:event_menuPlikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PanelTextowy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JMenuItem menuOProdramie;
    private javax.swing.JMenu menuPlik;
    private javax.swing.JMenu menuPomoc;
    private javax.swing.JMenuItem menuWczytaj;
    private javax.swing.JMenuItem menuZakoncz;
    private javax.swing.JMenuItem menuZamknij;
    private javax.swing.JMenuItem menuZapisz;
    private javax.swing.JDialog oknoOProgramie;
    private javax.swing.JFileChooser oknoZapisz;
    private javax.swing.JFileChooser onkoOtworz;
    private javax.swing.JOptionPane opcjaZapisu;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextPane poleTextowe;
    private javax.swing.JTabbedPane tab1;
    private javax.swing.JTabbedPane tab2;
    private javax.swing.JTabbedPane tab3;
    // End of variables declaration//GEN-END:variables
}
